---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-secrets
  namespace: flux-secrets
spec:
  values:
    additionalArgs:
      - --git-sync-tag=flux-sync-dev
    git:
      branch: "master"
      path: "sealed-secrets/dev"
