---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  annotations:
    flux.weave.works/automated: "false"
  name: flux-secrets
  namespace: flux-secrets
spec:
  chart:
    name: flux
    repository: https://charts.fluxcd.io
    version: 1.3.0
  releaseName: flux-secrets
  values:
    image:
      repository: docker.io/fluxcd/flux
      tag: 1.19.0

    git:
      url: "git@github.com:swade1987/kubernetes-secrets"
      pollInterval: "30s"
      secretName: "flux-git-deploy"

    memcached:
      enabled: false
      hostnameOverride: memcached.flux.svc.cluster.local

    registry:
      disableScanning: true

    sync:
      timeout: 2m
      interval: 2m

    syncGarbageCollection:
      enabled: true

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - flux
              topologyKey: kubernetes.io/hostname

    prometheus:
      enabled: true

    resources:
      requests:
        cpu: 400m
        memory: 1Gi
      limits:
        cpu: 400m
        memory: 1Gi
