apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-psp
  namespace: flux-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:flux-secrets
